[global]
# Configuraci贸n global para el despliegue web

[server]
# Configuraci贸n del servidor para despliegue web
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false

[theme]
# Tema personalizado (opcional)
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
# Configuraci贸n de logs
level = "info"